# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: David Biehl
email: me@davidbiehl.com
description: > 
  Thoughts on life and technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://davidbiehl.com" # the base hostname & protocol for your site
twitter_username: david_biehl
github_username:  davidbiehl

# Build settings
markdown: kramdown
